version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./storage:/storage
      - ./docker/php-fpm/conf.d/ah.conf:/usr/local/etc/php-fpm.d/ah.conf
      - ./docker/php-fpm/uploads.ini:/usr/local/etc/php/uploads.ini
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: database-demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 3452:5432
    environment:
      POSTGRES_PASSWORD: 123456

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8889:8080

  webserver:
    image: nginx:1.17-alpine
    ports:
      - 8888:80
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app

volumes:
  pgdata:
